---
language: elixir
elixir:
  - 1.7.4
  - 1.8.0
otp_release:
  - 21.0
  - 20.3
  - 19.3

matrix:
  exclude:
    - otp_release: 19.3
      elixir: 1.8.0

script:
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.4" ]; then mix format --check-formatted --dry-run; fi
  - MIX_ENV=test mix compile && mix test
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.4" ] && [ "$TRAVIS_OTP_RELEASE" = "21.0" ]; then mix dialyzer; fi
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.4" ] && [ "$TRAVIS_OTP_RELEASE" = "21.0" ]; then mix coveralls.travis; fi

cache:
  directories:
    - .mix
    - _build
